# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true

# Debug usa solo arm64-v8a (más rápido). Para release se pasa por CLI.
# ./gradlew <task> -PreactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
reactNativeArchitectures=arm64-v8a,x86_64

hermesEnabled=true
edgeToEdgeEnabled=false
